buildscript {
	ext.kotlin_version = '1.9.24'
	repositories {
		google()
		mavenCentral()
	}
	dependencies {
		classpath 'com.android.tools.build:gradle:8.9.2'
		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
		classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.8.9'
	}
	System.setProperty("dexguard.license", "${projectDir}/dexguard-license.txt")
}

plugins {
	id 'jacoco'
}

allprojects {
	repositories {
		google()
		mavenCentral()
		flatDir { dirs 'src/libs' }
	}

	ext {
		compileSdkVersion = 35
		minSdkVersion = 26
		targetSdkVersion = 35
		libsPath = "${projectDir}/libs"
	}
}

task clean(type: Delete) { delete rootProject.buildDir }