buildscript { 
	repositories { 
		google()
		jcenter()
	}

	dependencies { classpath 'com.android.tools.build:gradle:8.9.2' }
}

allprojects { 
	repositories { 
		google()
		jcenter()
		flatDir { dir "${rootProject.projectDir}/lib/fido2" }
	}
}

task clean(type: Delete) { delete rootProject.buildDir }