apply plugin: 'com.android.application'

android {

    defaultConfig {
        applicationId "com.thalesgroup.gemalto.fido2.sample"
        minSdkVersion 26
        compileSdk 35
        targetSdkVersion 35
        versionCode 1
        versionName "1.1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        fido {
            storeFile     file('sign.keystore')
            storePassword 'thalesfido2'
            keyAlias      'alias'
            keyPassword   'thalesfido2'
        }
    }

    buildFeatures {
        compose true
        buildConfig true //this line enables BuildConfig generation
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.fido
        }

        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.fido
        }
    }



    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'com.thalesgroup.gemalto.fido2.sample'
    lint {
        abortOnError false
        checkReleaseBuilds false
    }

}

dependencies {
    implementation project(":lib:fido2ui")
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.8.9'
    implementation 'androidx.navigation:navigation-ui-ktx:2.8.9'
    implementation "androidx.biometric:biometric:1.1.0"
    implementation 'net.java.dev.jna:jna:5.17.0@aar'
    implementation 'com.google.android.gms:play-services-fido:20.0.1'
}
